[MODULE]
order = 0
mandatory = [ "OBJECT" ]
optional = [ "ENUM" ]

[OBJECT]
order = 1
exclusive = true
mandatory = [ "ATTRIBUTE" ]
optional = [ "DESCRIPTION", "PARENT" ]
forbidden = [ "DataModel" ]

[DESCRIPTION]
order = 2

[ATTRIBUTE]
order = 2
exclusive = true
mandatory = [ "TYPE", "ATTRDESCRIPTION!" ]
optional = [ "PARENT", "REQUIRED", "OPTION", "MULTIPLE" ]
forbidden = [ "yield", "list", "dict", "return", "def", "class" ]

[OPTION]
order = 3
pattern = "^[A-Za-z0-9_]*\\s*\\:\\s*.*"

[TYPE]
order = 3
occurs_in = [ "OBJECT", "ENUM", "sdRDM.generator.datatypes@DataTypes" ]

[ATTRDESCRIPTION]
order = 3

[REQUIRED]
order = 3

[MULTIPLE]
order = 3

[PARENT]
order = 3
occurs_in = [ "OBJECT" ]

[ENUM]
order = 1
exclusive = true
mandatory = [ "MAPPING" ]

[MAPPING]
order = 2
exclusive = true
pattern = "^[A-Z][A-Z_0-9]*\\s?=\\s?\"[A-Za-z0-9@_!#$%^&*()<>?/|}{~:\\s ]*\""

[ENDOFMODEL]
order = 0

[HEADING]
order = 0
