name: Build and publish

on:
  release:
    types: [released]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: "Build and publish to PyPi"
          uses: JRubics/poetry-publish@v1.17
          with:
            pypi_token: ${{ secrets.PYPI_TOKEN }}